# Change these first
owner: deer-wmde # Your GitHub organization or username, where this repository lives
repo: wikibase-dev-uptime # The name of this repository

sites:
  - name: Frontend
    url: https://www.wikibase.dev/
  - name: API
    url: https://api.wikibase.dev/healthz
  - name: Mediawiki
    url: https://coffeebase.wikibase.dev/
  - name: Wikibase
    url: https://coffeebase.wikibase.dev/wiki/Item:Q1
  - name: CirrusSearch
    url: https://coffeebase.wikibase.dev/w/api.php?action=wbsearchentities&search=q1&format=json&errorformat=plaintext&language=en&uselang=en&type=item

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /wikibase-dev-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: wikibase.dev Status Page
  introTitle: "TEST wikibase.dev"
  introMessage: This Status Page is just a test instance. wikibase.dev is the staging deployment of wikibase.cloud. This page shows the status of the different components.
  navbar:
    - title: Status
      href: /
    - title: wikibase.dev
      href: https://wikibase.dev
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
